version: "3.1"

services:

  api:
    image: livesd/dependency-manager
    restart: unless-stopped
    build:
      context: ./dependency-manager/
      dockerfile: Dockerfile
    volumes:
      - ./dependency-manager/:/app
      - /app/node_modules
    ports:
      - 8002:3000
    env_file: 
      - dependency-manager/.env

  dependency-graph-visualizer:
    image: livesd/dependency-graph-visualizer
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 8001:3000
    env_file: 
      - frontend/.env  
