FROM node:16-alpine3.11

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# add app
COPY . ./

# expose port
EXPOSE 3000

CMD [ "yarn", "start" ]